### ISSUE TITLE
Application freeze when youtube-dl process an invalid url

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#127]
Application will freeze during youtube process for invalid url, 
example url: https://vod.tvp.pl/video/rozmowy-

reasons: unknown

**Comment by pyIDM** [comment]
it turns out this url  https://vod.tvp.pl/video/rozmowy-  will be redirected to https://vod.tvp.pl/ which have too many videos and youtube-dl will take several minutes trying to "Extract information" and finally gives "unsupported url" message
during these minutes the cpu usage will rise to 25%  and PyIDM GUI will freeze which shouldn't do this since youtube-dl run from a different thread
more investigation is required

**Comment by pyIDM** [comment]
Same effect with a test gui made of tkinter, gui will freeze when youtube-dl trying to "Extract information"

code:

```
import tkinter as tk
from tkinter import ttk
from threading import Thread
import youtube_dl as ytdl


def foo(url):
    if not url:
        print('input valid url and try again')
        return

    with ytdl.YoutubeDL() as ydl:
        # process=False is faster and youtube-dl will not download every videos webpage in the playlist
        info = ydl.extract_info(url, download=False, process=True)
    
    print(info)

root = tk.Tk()
root.config(bg='grey')
root.geometry('+300+300')

url_variable = tk.StringVar()
url_variable.set('https://vod.tvp.pl/')
url_text = ttk.Entry(root, width=40, textvariable=url_variable)
url_text.grid(row=0, column=0, columnspan=2)

tk.Button(root, text='test', command=lambda: print('GUI still responsive')).grid(row=1, column=0)
go_btn = tk.Button(root, text='Go',command=lambda: Thread(target=foo, args=[url_variable.get()]).start())
go_btn.grid(row=1, column=1)

for w in root.winfo_children():
    w.grid(pady=5, padx=5)

root.mainloop()

```

**Comment by pyIDM** [comment]
same effect with PySimpleGUIQt with url https://vod.tvp.pl/ 

code:

```
import PySimpleGUIQt as sg
from threading import Thread
import youtube_dl as ytdl


def foo(url):
    with ytdl.YoutubeDL() as ydl:
        # process=False is faster and youtube-dl will not download every videos webpage in the playlist
        info = ydl.extract_info(url, download=False, process=True)
    
    print(info)

layout = [
    [sg.I('', key='url', size=(50, 1))],
    [sg.B('Go')],
    [sg.B('test')]
]

window = sg.Window('', layout, finalize=True)

while True:
    event, values = window(timeout=10)
    if event is None:
        window.close()
        break
    elif event == 'test':
        print('test is working')
    elif event == 'Go':
        url = window['url'].get()
        Thread(target=foo, args=[url]).start()
```

**Comment by pyIDM** [comment]
tried with command line, cpu usage 25% youtube-dl freeze for 3 minutes trying to "Extract information"

```
[xx@xx-pc ~]$ youtube-dl -v -F https://vod.tvp.pl/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://vod.tvp.pl/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-4.19.126-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vod.tvp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vod.tvp: Downloading webpage
[generic] vod.tvp: Extracting information
ERROR: Unsupported URL: https://vod.tvp.pl/
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/xx/.local/lib/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vod.tvp.pl/

```

**Comment by pyIDM** [comment]
reported to youtube-dl and it has been fixed 
issue:
https://github.com/ytdl-org/youtube-dl/issues/25969
