### ISSUE TITLE
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)

### ISSUE THREAD

**Issue by myartsev** [pyIDM/PyIDM#165]
Hi!

Trying to get PyIDM running on OSX and running into a start-up issue after installation.
```
➜ ~ pyidm
Traceback (most recent call last):
  File "/usr/local/bin/pyidm", line 5, in <module>
    from pyidm.PyIDM import main
  File "/usr/local/lib/python3.7/site-packages/pyidm/PyIDM.py", line 48, in <module>
    from .controller import Controller
  File "/usr/local/lib/python3.7/site-packages/pyidm/controller.py", line 24, in <module>
    from . import update
  File "/usr/local/lib/python3.7/site-packages/pyidm/update.py", line 27, in <module>
    from .utils import log, download, run_command, delete_folder, version_value, delete_file
  File "/usr/local/lib/python3.7/site-packages/pyidm/utils.py", line 17, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
```

I installed PyIDM via, if that plays a role?
```
pip3 install pyidm --upgrade --no-cache
```

**Comment by pyIDM** [comment]
@myartsev 
this error is related to installing pycurl on mac,  
have a look at this post and give it a try, it might solve the problem
https://stackoverflow.com/a/21099222

**Comment by myartsev** [comment]
Spot on, thank you!
