### ISSUE TITLE
`pyidm` error: `_tkinter.TclError: unknown option "-style"`

### ISSUE THREAD

**Issue by muyinliu** [pyIDM/PyIDM#175]
```shell
pyidm
```
=>
```=>
>> Load Application setting from /usr/local/lib/python3.8/site-packages/pyidm
>> setting.cfg not found
>> Load previous download items from /usr/local/lib/python3.8/site-packages/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> downloads.cfg file not found
>> load_json() > error:  [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/pyidm/user_themes.cfg'
Traceback (most recent call last):
  File "/usr/local/bin/pyidm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pyidm/PyIDM.py", line 54, in main
    c = Controller(view_class=MainWindow)
  File "/usr/local/lib/python3.8/site-packages/pyidm/controller.py", line 138, in __init__
    self.view = view_class(controller=self)
  File "/usr/local/lib/python3.8/site-packages/pyidm/tkview.py", line 2353, in __init__
    self.create_main_widgets()
  File "/usr/local/lib/python3.8/site-packages/pyidm/tkview.py", line 2480, in create_main_widgets
    self.sett_frame = self.create_settings_tab()
  File "/usr/local/lib/python3.8/site-packages/pyidm/tkview.py", line 2577, in create_settings_tab
    tab = atk.ScrollableFrame(self.main_frame, bg=bg, sbar_fg=SBAR_FG, sbar_bg=SBAR_BG)
  File "/usr/local/lib/python3.8/site-packages/awesometkinter/frame.py", line 57, in __init__
    self.vsb = SimpleScrollbar(self.outer_frame, orient="vertical", command=self.canvas.yview, bg=sbar_bg, slider_color=sbar_fg)
  File "/usr/local/lib/python3.8/site-packages/awesometkinter/scrollbar.py", line 49, in __init__
    self.config(orient=orient, style=custom_style)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-style"
```

**Comment by pyIDM** [comment]
@muyinliu 
this is very weird error and i can not reproduce it
i will do more investigation and see how this happened

**Comment by pyIDM** [comment]
to narrow the problem, 
if you know how to execute python code you can try executing the following code
it should show you a small window with a button, if you click on the button it should change its color between green and red using "style" option

```
#!/usr/bin/env python
import tkinter as tk
from tkinter import ttk

root = tk.Tk()

s1 = 'style1.TButton'
s2 = 'style2.TButton'

s = ttk.Style()

s.map(s1, background=[('', 'red')])
s.map(s2, background=[('', 'green')])


iterator = ([s1, s2][i] for i in (0, 1))

selected_style = s1
def foo():
    global selected_style, btn

    print(selected_style)
    btn.config(style=selected_style)
    selected_style = s1 if selected_style == s2 else s2


btn = ttk.Button(root, text='click me', command=foo)
btn.pack()

root.mainloop()
```

please let me know if you get any error
