### ISSUE TITLE
Updated to version 2020.10.11 and then PyIDM cannot start

### ISSUE THREAD

**Issue by joectchan** [pyIDM/PyIDM#176]
I used an earlier version today and it worked fine. I was prompted to update. Did `python3 -m pip install  pyidm --upgrade --no-cache` to get the latest version. When I run again, GUI pops up briefly and goes away. I get these messages:
```
joseph@joseph-cb-laptop:~/workspace/github/pyIDM/PyIDM$ python3 -m pyidm
>> Load Application setting from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> Load previous download items from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> load_json() > error:  [Errno 2] No such file or directory: '/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/user_themes.cfg'
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
>> current working directory: /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  2659
  Current serial number in output stream:  2690
```
Please show me how to investigate further. I am a c programmer and know a tiny little bit of python. Given me some instructions to get me start please. Thanks.

**Comment by pyIDM** [comment]
@joectchan 
it looks like there is a font issue, lets change default font in pyidm files and see if it will fix this issue

from your log above, navigate to /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
then open tkview.py file with any text editor and you should find line number 2323 you will find below lines:

```
# root ----------------------------------------------------------------------------------------------------
self.root = tk.Tk()
```

now we should insert default font underneath these lines 
it will be something like:
```
# root ----------------------------------------------------------------------------------------------------
self.root = tk.Tk()

# default font
self.root.option_add("*Font", "helvetica") 

```

save the file and try to run pyidm again

**Comment by pyIDM** [comment]
> Serial number of failed request is different after adding default font.

i think we can try the version of pyidm you used before update and see if it is still working

you can install the older version by `pip install pyidm==version_number`

example you can install old gui version by
`pip install pyidm==2020.8.13`

**Comment by joectchan** [comment]
Attempted different font; same kind of error.
`        self.root.option_add("*Font", "FreeMono")`
```
>> Load Application setting from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> Load previous download items from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> load_json() > error:  [Errno 2] No such file or directory: '/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/user_themes.cfg'
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>> current working directory: /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  2674
  Current serial number in output stream:  2705
```

**Comment by joectchan** [comment]
Revert to 2020.8.13 and it continues to work.

**Comment by joectchan** [comment]
Log from 2020.8.13. Just in case it might help
```
>> Warning!! "pystray" package is required for systray icon, import error Namespace AppIndicator3 not available
>> clipboard needs "xsel", or "xclip" installed to run properly
>> Solo state can not be verified, moving on... 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> clipboard error: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
>> -------------------------------------------------- PyIDM --------------------------------------------------
>> Starting PyIDM version: 2020.8.13 Non-Frozen
>> systray: tray_icon name 'io' is not defined
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>> PySimpleGUI: 4.29.0 Released 25-Aug-2020
>> current working directory: /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> youtube-dl ready
>> Load Application setting from /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> setting.cfg not found
>> Load previous download items from /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> downloads.cfg file not found
>> tkinter version: 8.6.8
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
```

**Comment by pyIDM** [comment]
This is interesting
could you try this python code and see which font is triggering this error

python code:


```
import tkinter as tk
from tkinter import font
import awesometkinter as atk

root = tk.Tk()
root.title('Font Families')
fonts = list(font.families())
fonts.sort()
print(fonts)

f = atk.ScrollableFrame(root)
f.pack(expand=True, fill='both')

i = 1
def show_font():
    global i
    font_item = fonts.pop()
    print(i, font_item)
    tk.Label(f, text=f'{i}- {font_item}', font=(font_item, 16)).pack()
    root.after(100, show_font)

    i += 1


show_font()

root.mainloop()
```

this code will use all your installed fonts one by one, and you can try any font name that shows successfully on gui

i tried on my system and this font triggered the error

```
Noto Color Emoji
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  33501
  Current serial number in output stream:  33509
```

**Comment by joectchan** [comment]
The loop breaks when testing Color Emoji on my ubuntu 18.04 too.
```
58 Noto Color Emoji
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  4033
  Current serial number in output stream:  4043
```

**Comment by joectchan** [comment]
Edited the script to skip 58 Noto Color Emoji. All other fonts do not cause error. The final error kicks in when I try to pop an empty list.
```
python3 test_font.py 
['Abyssinica SIL', 'Ani', 'AnjaliOldLipi', 'Bitstream Charter', 'Century Schoolbook L', 'Chandas', 'Chilanka', 'Courier 10 Pitch', 'DejaVu Sans', 'DejaVu Sans Mono', 'DejaVu Serif', 'Dingbats', 'Droid Sans Fallback', 'Dyuthi', 'FreeMono', 'FreeSans', 'FreeSerif', 'Gargi', 'Garuda', 'Gubbi', 'Jamrul', 'KacstArt', 'KacstBook', 'KacstDecorative', 'KacstDigital', 'KacstFarsi', 'KacstLetter', 'KacstNaskh', 'KacstOffice', 'KacstOne', 'KacstPen', 'KacstPoster', 'KacstQurn', 'KacstScreen', 'KacstTitle', 'KacstTitleL', 'Kalapi', 'Kalimati', 'Karumbi', 'Keraleeyam', 'Khmer OS', 'Khmer OS System', 'Kinnari', 'LKLUG', 'Laksaman', 'Lato', 'Lato', 'Lato', 'Lato', 'Lato', 'Lato', 'Lato', 'Lato', 'Liberation Mono', 'Liberation Sans', 'Liberation Sans Narrow', 'Liberation Serif', 'Likhan', 'Lohit Assamese', 'Lohit Bengali', 'Lohit Devanagari', 'Lohit Gujarati', 'Lohit Gurmukhi', 'Lohit Kannada', 'Lohit Malayalam', 'Lohit Odia', 'Lohit Tamil', 'Lohit Tamil Classical', 'Lohit Telugu', 'Loma', 'Manjari', 'Manjari', 'Manjari', 'Meera', 'Mitra Mono', 'Mukti Narrow', 'Mukti Narrow', 'Nakula', 'Navilu', 'Nimbus Mono L', 'Nimbus Roman No9 L', 'Nimbus Sans L', 'Norasi', 'Noto Color Emoji', 'Noto Mono', 'Noto Sans CJK HK', 'Noto Sans CJK JP', 'Noto Sans CJK KR', 'Noto Sans CJK SC', 'Noto Sans CJK TC', 'Noto Sans Mono CJK HK', 'Noto Sans Mono CJK JP', 'Noto Sans Mono CJK KR', 'Noto Sans Mono CJK SC', 'Noto Sans Mono CJK TC', 'Noto Serif CJK JP', 'Noto Serif CJK KR', 'Noto Serif CJK SC', 'Noto Serif CJK TC', 'Padauk', 'Padauk Book', 'Pagul', 'Phetsarath OT', 'Pothana2000', 'Purisa', 'Rachana', 'RaghuMalayalam', 'Rekha', 'Saab', 'Sahadeva', 'Samanata', 'Samyak Devanagari', 'Samyak Gujarati', 'Samyak Malayalam', 'Samyak Tamil', 'Sarai', 'Sawasdee', 'Standard Symbols L', 'Suruma', 'Tibetan Machine Uni', 'Tlwg Mono', 'Tlwg Typewriter', 'Tlwg Typist', 'Tlwg Typo', 'URW Bookman L', 'URW Chancery L', 'URW Gothic L', 'URW Palladio L', 'Ubuntu', 'Ubuntu', 'Ubuntu Condensed', 'Ubuntu Mono', 'Umpush', 'Uroob', 'Vemana2000', 'Waree', 'aakar', 'mry_KacstQurn', 'ori1Uni', 'padmaa', 'padmaa-Bold.1.1']
1 padmaa-Bold.1.1
2 padmaa
3 ori1Uni
4 mry_KacstQurn
5 aakar
6 Waree
7 Vemana2000
8 Uroob
9 Umpush
10 Ubuntu Mono
11 Ubuntu Condensed
12 Ubuntu
13 Ubuntu
14 URW Palladio L
15 URW Gothic L
16 URW Chancery L
17 URW Bookman L
18 Tlwg Typo
19 Tlwg Typist
20 Tlwg Typewriter
21 Tlwg Mono
22 Tibetan Machine Uni
23 Suruma
24 Standard Symbols L
25 Sawasdee
26 Sarai
27 Samyak Tamil
28 Samyak Malayalam
29 Samyak Gujarati
30 Samyak Devanagari
31 Samanata
32 Sahadeva
33 Saab
34 Rekha
35 RaghuMalayalam
36 Rachana
37 Purisa
38 Pothana2000
39 Phetsarath OT
40 Pagul
41 Padauk Book
42 Padauk
43 Noto Serif CJK TC
44 Noto Serif CJK SC
45 Noto Serif CJK KR
46 Noto Serif CJK JP
47 Noto Sans Mono CJK TC
48 Noto Sans Mono CJK SC
49 Noto Sans Mono CJK KR
50 Noto Sans Mono CJK JP
51 Noto Sans Mono CJK HK
52 Noto Sans CJK TC
53 Noto Sans CJK SC
54 Noto Sans CJK KR
55 Noto Sans CJK JP
56 Noto Sans CJK HK
57 Noto Mono
Skip:  58 Noto Color Emoji
59 Norasi
60 Nimbus Sans L
61 Nimbus Roman No9 L
62 Nimbus Mono L
63 Navilu
64 Nakula
65 Mukti Narrow
66 Mukti Narrow
67 Mitra Mono
68 Meera
69 Manjari
70 Manjari
71 Manjari
72 Loma
73 Lohit Telugu
74 Lohit Tamil Classical
75 Lohit Tamil
76 Lohit Odia
77 Lohit Malayalam
78 Lohit Kannada
79 Lohit Gurmukhi
80 Lohit Gujarati
81 Lohit Devanagari
82 Lohit Bengali
83 Lohit Assamese
84 Likhan
85 Liberation Serif
86 Liberation Sans Narrow
87 Liberation Sans
88 Liberation Mono
89 Lato
90 Lato
91 Lato
92 Lato
93 Lato
94 Lato
95 Lato
96 Lato
97 Laksaman
98 LKLUG
99 Kinnari
100 Khmer OS System
101 Khmer OS
102 Keraleeyam
103 Karumbi
104 Kalimati
105 Kalapi
106 KacstTitleL
107 KacstTitle
108 KacstScreen
109 KacstQurn
110 KacstPoster
111 KacstPen
112 KacstOne
113 KacstOffice
114 KacstNaskh
115 KacstLetter
116 KacstFarsi
117 KacstDigital
118 KacstDecorative
119 KacstBook
120 KacstArt
121 Jamrul
122 Gubbi
123 Garuda
124 Gargi
125 FreeSerif
126 FreeSans
127 FreeMono
128 Dyuthi
129 Droid Sans Fallback
130 Dingbats
131 DejaVu Serif
132 DejaVu Sans Mono
133 DejaVu Sans
134 Courier 10 Pitch
135 Chilanka
136 Chandas
137 Century Schoolbook L
138 Bitstream Charter
139 AnjaliOldLipi
140 Ani
141 Abyssinica SIL
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "test_font.py", line 17, in show_font
    font_item = fonts.pop()
IndexError: pop from empty list

```

**Comment by pyIDM** [comment]
can you install back the last pyidm version and try different fonts

`pip install pyidm --upgrade`

and try again to modify tkview.py file with different fonts

e.g.
```
# root ----------------------------------------------------------------------------------------------------
self.root = tk.Tk()

# default font
self.root.option_add("*Font", "DejaVu Sans") 

```

**Comment by pyIDM** [comment]
also the downloads.cfg file [if exists] should be moved away from pyidm folder temporarily, it might contains unreadable characters and trigger this error

**Comment by joectchan** [comment]
It does not like missing both downloads.cfg and user_themes.cfg files.
```
python3 -m pyidm
>> Load Application setting from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> Load previous download items from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> downloads.cfg file not found
>> load_json() > error:  [Errno 2] No such file or directory: '/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/user_themes.cfg'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/__main__.py", line 24, in <module>
    PyIDM.main()
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/PyIDM.py", line 54, in main
    c = Controller(view_class=MainWindow)
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/controller.py", line 138, in __init__
    self.view = view_class(controller=self)
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/tkview.py", line 2356, in __init__
    self.create_main_widgets()
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/tkview.py", line 2480, in create_main_widgets
    self.home_tab = self.create_home_tab()
  File "/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/tkview.py", line 2525, in create_home_tab
    fg=MAIN_FG, textvariable=self.url_var)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2676, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: expected integer but got "Sans"
```

**Comment by joectchan** [comment]
Hold on. It works when I invoke with just `pyidm` but not `python3 -m pyidm`

**Comment by joectchan** [comment]
```
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>> current working directory: /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
```

**Comment by joectchan** [comment]
I updated too fast without sufficient testing. Here is the current status.
I CAN invoke with `python3 -m pyidm`
I cannot use `self.root.option_add("*Font", "DejaVu Sans")` but I can use `self.root.option_add("*Font", "FreeSans")
I copied a youtube url. Try to download. Then it failed.
```
python3 -m pyidm
>> Load Application setting from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> Load previous download items from /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> downloads.dat file not found, looking for legacy "downloads.cfg" file
>> downloads.cfg file not found
>> load_json() > error:  [Errno 2] No such file or directory: '/home/joseph/workspace/github/pyIDM/PyIDM/pyidm/user_themes.cfg'
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>> current working directory: /home/joseph/workspace/github/pyIDM/PyIDM/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
url_watchdog, new url:  https://youtu.be/ypgB3iqg0b8
playlist here
>> start create video playlist
>> [youtube] ypgB3iqg0b8: Downloading webpage
>> video doesn't have subtitles
>> [youtube] ypgB3iqg0b8: Looking for automatic captions
>> downloading Thumbnail
>> controller> playlist ready
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> fresh file download
>> 

>> ==========================================================================================================
>> start downloading file: "USB and Development of USB Devices.mp4", size: 43.0 MB, to: /home/joseph/Videos 

>> Thread Manager()> concurrency method: Individual Threads
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  12727
  Current serial number in output stream:  12735

```

**Comment by pyIDM** [comment]
what about running pyidm.py directly
e.g.

`python3 /home/joseph/.local/lib/python3.6/site-packages/pyidm/pyidm.py`

any difference?

**Comment by joectchan** [comment]
Tried. Same behavior. GUI comes up; try download the same USB tutorial video from youtube; die.
Does it still look like font issue?
```
python3 /home/joseph/.local/lib/python3.6/site-packages/pyidm/PyIDM.py 
>> Load Application setting from /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> Load previous download items from /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
>> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>> current working directory: /home/joseph/.local/lib/python3.6/site-packages/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
url_watchdog, new url:  https://youtu.be/ypgB3iqg0b8
>> get_headers()> getting headers for: https://youtu.be/ypgB3iqg0b8
>> Segments-ypgB3iqg0b8.htm, (1): ['0:None']
>> headers: {'content-length': '0', 'location': 'https://www.youtube.com/watch?v=ypgb3iqg0b8&feature=youtu.be', 'date': 'thu, 15 oct 2020 19:02:46 gmt', 'content-type': 'text/html; charset=utf-8', 'server': 'youtube frontend proxy', 'x-xss-protection': '0', 'alt-svc': 'h3-q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-t051=":443"; ma=2592000,h3-t050=":443"; ma=2592000,h3-q046=":443"; ma=2592000,h3-q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'strict-transport-security': 'max-age=31536000', 'x-frame-options': 'sameorigin', 'cache-control': 'no-cache', 'expires': 'tue, 27 apr 1971 19:44:06 gmt', 'x-content-type-options': 'nosniff', 'p3p': 'cp="this is not a p3p policy! see http://support.google.com/accounts/answer/151657?hl=en for more info."', 'set-cookie': 'ysc=wc7nxy-neby; path=/; domain=.youtube.com; secure; httponly; samesite=none', 'accept-ranges': 'none', 'vary': 'accept-encoding', 'transfer-encoding': 'chunked', 'status_code': 200, 'eff_url': 'https://www.youtube.com/watch?v=ypgB3iqg0b8&feature=youtu.be'}
playlist here
>> start create video playlist
>> [youtube] ypgB3iqg0b8: Downloading webpage
>> video doesn't have subtitles
>> [youtube] ypgB3iqg0b8: Looking for automatic captions
>> Segments-USB and Development of USB Devices.mp4, (10): ['0:[0, 4508822]', '1:[4508823, 9017645]', '2:[9017646, 13526468]', '3:[13526469, 18035291]', '4:[18035292, 22544114]', '5:[22544115, 27052937]', '6:[27052938, 31561760]', '7:[31561761, 36070583]', '8:[36070584, 40579406]', '9:[40579407, 45088232]']
>> downloading Thumbnail
>> controller> playlist ready
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> fresh file download
>> 

>> ==========================================================================================================
>> start downloading file: "USB and Development of USB Devices.mp4", size: 43.0 MB, to: /home/joseph/Videos 

>> Segments-USB and Development of USB Devices.mp4, (10): ['0:[0, 4508822]', '1:[4508823, 9017645]', '2:[9017646, 13526468]', '3:[13526469, 18035291]', '4:[18035292, 22544114]', '5:[22544115, 27052937]', '6:[27052938, 31561760]', '7:[31561761, 36070583]', '8:[36070584, 40579406]', '9:[40579407, 45088232]']
>> Thread Manager()> concurrency method: Individual Threads
>> Thread Manager: allowable connections: 2
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  5466
  Current serial number in output stream:  5474
```

**Comment by pyIDM** [comment]
> Does it still look like font issue?
yes i think so, "RenderAddGlyphs" is related to fonts
also there is a bug on ubuntu launchpad referring to this issue at https://bugs.launchpad.net/ubuntu/+source/git/+bug/1852985

**Comment by joectchan** [comment]
I found that tag 2020.9.20 is working on my computer. Then I `git bisect` between 2020.9.20 and 2020.10.10. Git found that
```
b5ebcc7bb857be5cdef52e307b0f1ec9eea25c97 is the first bad commit
commit b5ebcc7bb857be5cdef52e307b0f1ec9eea25c97
Author: pyIDM <mahmoud.aboghazala@gmail.com>
Date:   Sat Oct 3 00:51:19 2020 +0200

    Added Schedule downloads feature

:040000 040000 84e4ee4827e521450f56527f42a39c5cd36bce02 82a1d3897143981e690f7da4a0219dd74d95a02f M	pyidm
```

```
b5ebcc7 (HEAD, refs/bisect/bad) Added Schedule downloads feature
216b28e (refs/bisect/good-216b28e0d771407d96fc43f5a183a3ec002a4d07) added log level menu in log tab
d8bdc94 popup focus
8272b35 fixed undeleted metadata temp file in case of exceptions
06969ce Added help button in about notes
97ca434 used new format for downloads and thumbnail files
0c91669 fix for rendered name if title is missing
1e605e1 added button to open settings folder
e70cbb7 handle DItem update exception
1921407 fixed remaining errors field after item "completed"
b268c3e ignore a pending item if cancelled before it get started.
15b8923 Added browse button to select cookies file
362c7d7 updated readme
f30c5d1 Created user guide
406d65e deleted cookies.md and proxy.md doc files
016d783 fixed arabic file names display on linux
ae1e9b7 updated resume warning
c2ed681 added option to enable/disable systray icon, "disabled by default except on Windows"
24226b9 return None audio menu for non video streams
7af4e33 used rendered name instead of name in properties window
2fbcfea moved download temp files into one temp folder
7c555d6 fix for download folder, issue #164
edba8be added copy log button
e1541a6 block until closing audio window
b9068b4 handle pending downloads
d20dbda replaced standard radiobutton with awesometkinter radiobutton
e181b28 manual audio selection for dash videos
4f3f443 add exception for "get_thumbnail()" in base class
1b940f7 fixed exception when uid is not in d_map
c24f379 improved docstrings
94ce027 [cleanup] removed unnecessary Progressbar class
0338d70 (tag: 2020.9.20, refs/bisect/good-0338d70c05a4ea2f761de2c5f1775c9087131162) version 2020.9.20
```
I am sticking to 216b28e, which is the latest good version for my computer. I have not `git diff` between the last good and the first bad commit. It is kind of late now. I will see if I can get back to this Sunday. Don't know my level of python can offer any insight for you, but I will try.

**Comment by joectchan** [comment]
I read the diff between the last good and first bad commits. Scheduling and DatePickerWindow are the major additions. I feel like this is beyond my current level of Python/TK. Hope I have exposed enough info for further investigation. Let me if there is anything I can test.

**Comment by pyIDM** [comment]
@joectchan 
I suspect the reason is the use of symbols in the last version
if you can test the latest version but modifying tkview.py file

delete or comment out line number 1493 
`self.status_symbol.set(self.animation_symbols.get(status, ''))`

delete '▼' symbol from line number 1381 
`self.blinker = tk.Label(btns_frame, bg=self.bg, text='▼', fg='green')` 

should be `self.blinker = tk.Label(btns_frame, bg=self.bg, text='', fg='green')`

please test and let me know if it works for you

**Comment by joectchan** [comment]
Made the above two line changes. GUI still quits. BTW, I grab another PC with ubuntu 20.04; just in case 18.04 is too old. Saw the same error.
```
>> Load Application setting from /home/joseph/ws/github/pyidm/PyIDM/pyidm
>> Load previous download items from /home/joseph/ws/github/pyidm/PyIDM/pyidm
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-42-generic-x86_64-with-glibc2.29 - x86_64
>> Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
>> current working directory: /home/joseph/ws/github/pyidm/PyIDM/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
url_watchdog, new url:  https://www.youtube.com/watch?v=ZAji7PkXaKY&list=PLHTh1InhhwT6VxYHtoWIvOup9gz0p95Qr
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  3026
  Current serial number in output stream:  3058
```

**Comment by pyIDM** [comment]
can you check which tkinter version installed on your system by running this code

```
import tkinter
root = tkinter.Tk()
print(root.tk.call("info", "patchlevel"))
root.destroy()
```

there is a ticket already in tk reporting this issue and said it has been fixed on 2020-04-14: 
https://core.tcl-lang.org/tk/tktview/3767882e066523dc9ae4475dbdcb6c33dfe57c6b

will do more testing to hunt this error

**Comment by pyIDM** [comment]
some suggested workaround is to install fonts-symbola

`sudo apt install fonts-symbola`

**Comment by joectchan** [comment]
> can you check which tkinter version installed on your system by running this code
> 
> ```
> import tkinter
> root = tkinter.Tk()
> print(root.tk.call("info", "patchlevel"))
> root.destroy()
> ```
> 
> there is a ticket already in tk reporting this issue and said it has been fixed on 2020-04-14:
> https://core.tcl-lang.org/tk/tktview/3767882e066523dc9ae4475dbdcb6c33dfe57c6b
> 
> will do more testing to hunt this error

On ubuntu18.04, I got 
8.6.8

On ubuntu20.04, I got
8.6.10

**Comment by joectchan** [comment]
Installing fonts-symbola works for me. Tested on both ubuntu 18.04 and 20.04. Can use the latest commit. GUI stays functional. Can download video. Thanks for helping.

**Comment by pyIDM** [comment]
> Installing fonts-symbola works for me. Tested on both ubuntu 18.04 and 20.04. Can use the latest commit. GUI stays functional. Can download video. Thanks for helping.

This is great news 
closing this issue

**Comment by joectchan** [comment]
As I perform a fresh install on a new ubuntu 20.04, I performed these steps to install a working pyidm. It would be good to update the readme.md with these steps.
```
git clone https://github.com/pyIDM/PyIDM.git
sudo apt install ffmpeg fonts-symbola libcurl4-openssl-dev libssl-dev python3-pip python3-pil python3-pil.imagetk python3-tk 
python3 setup.py install --user
python3 -m pyidm
```

**Comment by pyIDM** [comment]
> As I perform a fresh install on a new ubuntu 20.04, I performed these steps to install a working pyidm. It would be good to update the readme.md with these steps.
> 
> ```
> git clone https://github.com/pyIDM/PyIDM.git
> sudo apt install ffmpeg fonts-symbola libcurl4-openssl-dev libssl-dev python3-pip python3-pil python3-pil.imagetk python3-tk 
> python3 setup.py install --user
> python3 -m pyidm
> ```

thanks for sharing 
will add in readme for other users to save them a lot of effort
