### ISSUE TITLE
pyidm TypeError: ellipse() got an unexpected keyword argument 'width'

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#201]
running on Linux Mint with old pillow version generate the following error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pyidm/__main__.py", line 24, in <module>
    PyIDM.main()
  File "/usr/local/lib/python3.6/dist-packages/pyidm/PyIDM.py", line 39, in main
    c = Controller(view_class=MainWindow)
  File "/usr/local/lib/python3.6/dist-packages/pyidm/controller.py", line 138, in __init__
    self.view = view_class(controller=self)
  File "/usr/local/lib/python3.6/dist-packages/pyidm/tkview.py", line 2634, in __init__
    self.create_main_widgets()
  File "/usr/local/lib/python3.6/dist-packages/pyidm/tkview.py", line 2763, in create_main_widgets
    self.home_tab = self.create_home_tab()
  File "/usr/local/lib/python3.6/dist-packages/pyidm/tkview.py", line 2821, in create_home_tab
    self.pl_menu = MediaListBox(home_tab, bg, 'Playlist:')
  File "/usr/local/lib/python3.6/dist-packages/pyidm/tkview.py", line 1034, in __init__
    self.bar = atk.RadialProgressbar(parent=self, size=(100, 100), fg=PBAR_FG, text_bg=self.background, text_fg=PBAR_TXT)
  File "/usr/local/lib/python3.6/dist-packages/awesometkinter/progressbar.py", line 67, in __init__
    self.bar_style = self.create_style()
  File "/usr/local/lib/python3.6/dist-packages/awesometkinter/progressbar.py", line 128, in create_style
    img = create_circle(self.size, color=self.fg)
  File "/usr/local/lib/python3.6/dist-packages/awesometkinter/utils.py", line 326, in create_circle
    draw.ellipse([offset, offset, size[0] - offset, size[1] - offset], outline=color, fill=fill_color, width=thickness)
TypeError: ellipse() got an unexpected keyword argument 'width'
```

**Comment by pyIDM** [comment]
minimum version of pillow should be higher than version 6
