### ISSUE TITLE
If there is no item on download list, click on "D.Window" closes the app.

### ISSUE THREAD

**Issue by 7aman** [pyIDM/pyIDM#39]
Hi. Thanks for your great app.

OS: windos10-64bit
Installed by PIP

I installed the app. I was exploring tabs and buttons on the GUI. There was no links to download. I clicked on "D.Window" and app was closed. This is the cmd output when this is happened.

```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pyidm.exe\__main__.py", line 7, in <module>
    :copyright: (c) 2019-2020 by Mahmoud Elshahat.
  File "c:\python\lib\site-packages\pyidm\pyIDM.py", line 108, in main
    main_window.run()
  File "c:\python\lib\site-packages\pyidm\gui.py", line 454, in run
    if self.selected_d.status == Status.downloading:
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by pyIDM** [comment]
Fixed this issue, commit 2364dc005a80c03c7e0db69f5beb6710fbb2e81e

I really do appreciate your active participation, without a valuable feedback like yours i can't improve this application, please keep these good things coming
:+1:
