### ISSUE TITLE
pyidm not working - on Linux

### ISSUE THREAD

**Issue by deepakah101** [pyIDM/PyIDM#85]
I get the following error when i try to run pyidm. Can you please help me out?
```
$ python3 -m pyidm 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aarya/.local/lib/python3.7/site-packages/pyidm/__main__.py", line 24, in <module>
    PyIDM.main()
  File "/home/aarya/.local/lib/python3.7/site-packages/pyidm/PyIDM.py", line 114, in main
    if not is_solo():
  File "/home/aarya/.local/lib/python3.7/site-packages/pyidm/PyIDM.py", line 91, in is_solo
    original = clipboard.paste()  # get original clipboard value
  File "/home/aarya/.local/lib/python3.7/site-packages/pyperclip/__init__.py", line 640, in lazy_load_stub_paste
    return paste()
  File "/home/aarya/.local/lib/python3.7/site-packages/pyperclip/__init__.py", line 157, in paste_gtk
    clipboardContents = gtk.Clipboard().wait_for_text()
  File "/home/aarya/.local/lib/python3.7/site-packages/gi/__init__.py", line 72, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```
Big fan of your IDM btw, but i'm not tech savvy, so please help me out. Thanks :) I even tried uninstalling and reinstalling.

**Comment by pyIDM** [comment]
@deepakah101 
Thanks for reporting this,
The problem happened because "pyperclip" the clipboard module use old gtk implementation, I already drop gtk and it will use alternative mechanism like xclip or xsel if its installed on Linux

will let you know once making a new  pypi release

**Comment by deepakah101** [comment]
Thank you so much :)

**Comment by pyIDM** [comment]
@deepakah101 
just made a pypi release 2020.5.18
hope it works properly on Linux :)

**Comment by deepakah101** [comment]
Yay! no more errors! just finished downloading a file.
Everything works perfectly smooth now!! thank you very much :) xoxoxo

**Comment by pyIDM** [comment]
This is Great!
