### ISSUE TITLE
Why the GUI is not zoomable?

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#98]
Hi,

I noted that the GUI's size of pyidm is not zoomable. Any hints for this problem?

Regards

**Comment by pyIDM** [comment]
By saying `zoomable` do you mean why window maximize button is disabled?

**Comment by hongyi-zhao** [comment]
Zoom with mouse drag or maximize/minimize button.

**Comment by pyIDM** [comment]
Designed new gui

**Comment by hongyi-zhao** [comment]
But still has the following problem:
```
$ pyidm 
>> Load Application setting from /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> load_json() > error:  [Errno 2] No such file or directory: '/home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm/user_themes.cfg'
>> youtube-dl version: 2020.06.06, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.9.20 Non-Frozen
>> operating system: Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5 - x86_64
>> Python version: 3.8.3 (default, May 25 2020, 15:44:25) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/idm-pydidm-xdm/PyIDM.git/pyidm
>> url watchdog active!
>> controller.get_d_list()> sending d_list
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 159, in _update_icon
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 140, in _show
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError
Gui terminated
Stop all downloads
>> setting saved
>> list saved
```

**Comment by pyIDM** [comment]
Oh!, thanks for reminding me
I will try to find a fix for systray icon
What is your current os and its version? Is it ubuntu?

**Comment by hongyi-zhao** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
